### ISSUE TITLE
Progress report TODO

### ISSUE THREAD

**Issue by ajinkyai** [ajinkyai/torqa#1]
You’ve had a few weeks to work on the project! You have now clarified and revised your proposed idea. You have started working on it and have some preliminary results to report.

The progress report is a 5-10 page document that describes your preliminary work and results. You should do and report on work including

- [x] Acquire your dataset. Report its source, its basic statistics (source, size, number of words/sentences/documents) and other important properties.
- [x] If your project involves annotation, you’ve started a pilot annotation experiment, annotating a few dozen or few hundred examples. What major issues have come up? Do you and your project partner agree or disagree on examples? (At this stage, qualitative findings about these questions are fine.)
- [ ] Run some sort of NLP algorithm — classifier, parser, etc. — on the data, and report its result. If you are using a ready-made dataset, you should define a train/test split, and you should have at least one accuracy number to report at this point.
- [x] The report must contain at least one table or graph that conveys numerical information – for example, statistics about your data or annotations, 
- [ ] Graph on accuracy or other results of running an algorithm on the data, or something else.
- [ ] You now have a better idea of how much you can accomplish in the rest of the semester. Lay out the major items you want to accomplish. Provide a timeline to finish them by.
